# Generated by Django 3.2.23 on 2024-01-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
