# Generated by Django 3.2.23 on 2024-01-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_email_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
