# Generated by Django 3.2.23 on 2024-01-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_username_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
